### ISSUE TITLE
Linking fails: missing `-ltraps` and `-lchecks`

### ISSUE THREAD

**Issue by jons-pf** [ORNL-Fusion/LIBSTELL#66]
Hi Mark,
I tried compiling PARVMEC today and the whole build fails due to linker errors about missing `-ltraps` and `-lchecks`.
I saw some traces of that here:
https://github.com/ORNL-Fusion/LIBSTELL/blob/42c0c96c2a1bb410cc03b863fc725eba1ecc41ff/CMakeLists.txt#L58
Can you please clarify if I need to do some additional setup/... on my machine?
Thanks, Jonathan

**Comment by cianciosa** [comment]
Make sure you do a git pull from the main project.

On Dec 16, 2024, at 1:02 AM, Jonathan Schilling ***@***.***> wrote:



Hi Mark,
I tried compiling PARVMEC today and the whole build fails due to linker errors about missing -ltraps and -lchecks.
I saw some traces of that here:
https://github.com/ORNL-Fusion/LIBSTELL/blob/42c0c96c2a1bb410cc03b863fc725eba1ecc41ff/CMakeLists.txt#L58<https://urldefense.us/v2/url?u=https-3A__github.com_ORNL-2DFusion_LIBSTELL_blob_42c0c96c2a1bb410cc03b863fc725eba1ecc41ff_CMakeLists.txt-23L58&d=DwMCaQ&c=v4IIwRuZAmwupIjowmMWUmLasxPEgYsgNI-O7C4ViYc&r=jHzqd7h8AUyesPAQHKZPYGMox50RMWt0Xdplk3LbqH8&m=y1TtL-EU15zyeoQjsoV-_qPcnFQdyujrbt3YuDkqLGKj4d6O3wfEosW5YHuNguu2&s=QejVNtmCT1NyFt78K0Xb8MHxafMKsoCYMOLBfUvF_xk&e=>
Can you please clarify if I need to do some additional setup/... on my machine?
Thanks, Jonathan

**Comment by jons-pf** [comment]
Thanks, that fixed it!
